name: CI

on:
  push:
    branches:
      - main
  pull_request:
env:
  CI: true
  TEST: true
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run check
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        id: playwright-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npm ci && npx playwright install

      - name: Run tests
        run: npm run test
